// js/apps/wechat/state.js — 微信模块内部状态
export const wxState = {
  view: 'main',
  activeTab: 'chats',
  activeChatId: null,
  showNewChatModal: false,
  showPlusMenu: false,
  isTyping: false,
  virtualModalType: 'none',
  activeTransferId: null,
  callType: null,
  callStartTime: null,
  pendingCallMsg: '',
  ringtone: new Audio('https://assets.mixkit.co/active_storage/sfx/1359/1359-preview.mp3'),
  savedScroll: 0,
  activeMenuMsgId: null,
  longPressTimer: null,
  quoteMsgId: null,
  isMultiSelecting: false,
  selectedMsgIds: [],
  expandedGroups: {},
  editingContactId: null,
  tempAvatar: null,
  editingPersonaId: null,
  editingEmojiLibId: null,
  favManageMode: false,
  selectedFavIds: [],
  tempPersonaAvatar: null,
  showEmojiMenu: false,
  activeEmojiTab: 0,
  showEmojiMountModal: false,
  showWbMountModal: false,
  activeWbGroup: '全部',
  showPersonaMountModal: false,
  tempBoundPersonaId: null,
  tempMomentImage: null,
  activeMomentMenuId: null,
  momentInput: { active: false, momentId: null, replyTo: null },
  showGlobalPromptModal: false,
  tempMomentVirtual: null,
  showForwardModal: false,
  forwardType: 'single',
  forwardMsgIds: [],
  showExtractMemoryModal: false,
  extractMemoryStep: 1,
  extractMemoryConfig: { roundCount: 20, type: 'fragment', keywords: '' },
  extractMemoryContent: '',
  isExtracting: false,
  newChatStep: 'chooseType',
  newGroupData: { members: [], name: '', personaId: null },
  revealingMsgIds: new Set(),
  // 🌟 会话内 blob URL 缓存：msgId -> blob URL。绝不持久化，刷新后清空让消息回退到 Minimax 重生成。
  voiceBlobCache: {},
};
wxState.ringtone.loop = true;
window.wxState = wxState; // 🌟 把微信内部状态暴露给全局，方便外部读取
